version: '2'

services:

  traefik:
    build: .
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 8000:8000/tcp
    environment:
      TRAEFIK_RANCHER_DOMAIN: $DEFAULT_DOMAIN
      TRAEFIK_HTTPS_ENABLE: "false"
