version: '2'

services:

  traefik:
    build: .
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 8000:8000/tcp
    environment:
      TRAEFIK_RANCHER_ENDPOINT: $RANCHER_SERVER
      TRAEFIK_RANCHER_ACCESS_KEY: $RANCHER_ACCESS_KEY
      TRAEFIK_RANCHER_SECRET_KEY: $RANCHER_SECRET_KEY
      TRAEFIK_RANCHER_DOMAIN: $DEFAULT_DOMAIN
      TRAEFIK_HTTPS_ENABLE: $HTTP_ENABLE
      TRAEFIK_SSL_CERT: $SSL_CERT
      TRAEFIK_SSL_KEY: $SSL_KEY
