version: '2'

services:

  traefik:
    image: nhsuk/traefik-rancher:${DOCKER_IMAGE_TAG}
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 8000:8000/tcp
    environment:
      TRAEFIK_RANCHER_DOMAIN: $DEFAULT_DOMAIN
      TRAEFIK_HTTPS_ENABLE: $TRAEFIK_HTTPS_ENABLE
      TRAEFIK_SSL_CERT: $SSL_CERT
      TRAEFIK_SSL_KEY: $SSL_KEY
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
    logging:
      driver: splunk
      options:
        splunk-url: ${SPLUNK_HEC_URL}
        splunk-token: ${SPLUNK_HEC_TOKEN}
        splunk-insecureskipverify: "true"
        splunk-sourcetype: traefik
        splunk-verify-connection: "false"
        tag: "{{`{{.ImageName}} {{.Name}} {{.FullID}}`}}"
        splunk-format: json
