version: '2'

services:
  traefik:
    image: nhsuk/traefik-rancher:${DOCKER_IMAGE_TAG}
    ports:
      - 80:80
      - 8000:8080
      - 443:443
    environment:
      RANCHER_SERVER: $RANCHER_SERVER
      RANCHER_ACCESS_KEY: $RANCHER_ACCESS_KEY
      RANCHER_SECRET_KEY: $RANCHER_SECRET_KEY
      DEFAULT_DOMAIN: $DEFAULT_DOMAIN
    logging:
      driver: splunk
      options:
        splunk-url: ${SPLUNK_HEC_URL}
        splunk-token: ${SPLUNK_HEC_TOKEN}
        splunk-insecureskipverify: "true"
        splunk-sourcetype: docker
        splunk-source: rancher-traefik
        splunk-verify-connection: "false"
        tag: "{{`{{.ImageName}} {{.Name}} {{.FullID}}`}}"
