version: '2'

services:

  traefik:
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      request_line: GET /ping HTTP/1.0
      port: 8000
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
